### ISSUE TITLE
erro ao tentar baixar do tsuki mangas

### ISSUE THREAD

**Issue by Trademarkpolicyy** [OneDefauter/Manga-Downloader#1]
estou recebendo esse erro ao tentar baixar do tsuki:

C:\Users\****\AppData\Local\Temp\main.py:2540: DeprecationWarning: There is no current event loop
  loop = asyncio.get_event_loop()

DevTools listening on ws://127.0.0.1:4698/devtools/browser/180a62a0-8ded-430b-a42d-d0423a991dfc

Aguarde...
Verificando capítulos...
Traceback (most recent call last):
  File "C:\Users\****\AppData\Local\Temp\main.py", line 2541, in <module>
    loop.run_until_complete(main())
  File "C:\Users\****\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 664, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\****\AppData\Local\Temp\main.py", line 1513, in main
    capitulos_solicitados = obter_capitulos(driver, capítulo, ate)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\*****\AppData\Local\Temp\main.py", line 1493, in obter_capitulos
    numero_capitulo = float(re.sub(r'[^0-9.,]', '', chapter_number.replace(',', '')))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: could not convert string to float: ''

**Comment by OneDefauter** [comment]
Esse erro foi corrigido e é causado porque não foi encontrado nenhum capítulo, mesmo havendo.
