### ISSUE TITLE
demora pra baixar do tsukimangas e não consegue baixar do lermangas.org e brmangas.net

### ISSUE THREAD

**Issue by Trademarkpolicyy** [OneDefauter/Manga-Downloader#2]
atualmente demora bastante pra iniciar os downloads do tsuki mangas e também pra começar o proximo download quando um termina, não sei se é temporario mas começou do nada a dar um erro ao tentar baixar do brmangas.net e lermangas.org ja faz alguns minutos.

brmangas:
Exception in thread Thread-4 (run_async_loop):
Traceback (most recent call last):
  File "C:\Users\****\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1052, in _bootstrap_inner
    self.run()
  File "C:\Users\****\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 989, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\rafae\AppData\Local\Temp\main.py", line 2800, in run_async_loop
    loop.run_until_complete(self.TkApp())
  File "C:\Users\****\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 664, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\****\AppData\Local\Temp\main.py", line 2635, in TkApp
    result = await agr_01(driver, url, capítulo, ate)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\****\AppData\Local\Temp\main.py", line 713, in agr_01
    await run(url, numero_capitulo, session)
  File "C:\Users\****\AppData\Local\Temp\main.py", line 686, in run
    div_imagens = driver.find_element(By.ID, 'images_all')
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\****\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 741, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\****\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\Users\****\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="images_all"]"}
  (Session info: headless chrome=119.0.6045.160); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
        GetHandleVerifier [0x00007FF6FFD082B2+55298]
        (No symbol) [0x00007FF6FFC75E02]
        (No symbol) [0x00007FF6FFB305AB]
        (No symbol) [0x00007FF6FFB7175C]
        (No symbol) [0x00007FF6FFB718DC]
        (No symbol) [0x00007FF6FFBACBC7]
        (No symbol) [0x00007FF6FFB920EF]
        (No symbol) [0x00007FF6FFBAAAA4]
        (No symbol) [0x00007FF6FFB91E83]
        (No symbol) [0x00007FF6FFB6670A]
        (No symbol) [0x00007FF6FFB67964]
        GetHandleVerifier [0x00007FF700080AAB+3694587]
        GetHandleVerifier [0x00007FF7000D728E+4048862]
        GetHandleVerifier [0x00007FF7000CF173+4015811]
        GetHandleVerifier [0x00007FF6FFDA47D6+695590]
        (No symbol) [0x00007FF6FFC80CE8]
        (No symbol) [0x00007FF6FFC7CF34]
        (No symbol) [0x00007FF6FFC7D062]
        (No symbol) [0x00007FF6FFC6D3A3]
        BaseThreadInitThunk [0x00007FFDE6547344+20]
        RtlUserThreadStart [0x00007FFDE7DC26B1+33]

**Comment by OneDefauter** [comment]
A demora para iniciar o Tsuki tanto carregar as paginas quanto baixar tem haver com a espera de carregar certos elementos (pretendo melhorar).
Quanto o BR Mangás, corrigi o problema (era por causa que eles mudaram uma coisa).
Sobre o Ler Mangá, não encontrei nenhum problema.
