### ISSUE TITLE
novo erro ao tentar baixar do Tsuki magnas

### ISSUE THREAD

**Issue by Trademarkpolicyy** [OneDefauter/Manga-Downloader#3]
agora começa o download mais rapido mas recebo esse erro ao tentar baixar do https://tsuki-mangas.com:

Exception in thread Thread-4 (run_async_loop):
Traceback (most recent call last):
  File "C:\Users\****\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1052, in _bootstrap_inner
    self.run()
  File "C:\Users\****\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 989, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\****\AppData\Local\Temp\main.py", line 3056, in run_async_loop
    loop.run_until_complete(self.TkApp())
  File "C:\Users\****\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 664, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\****\AppData\Local\Temp\main.py", line 2950, in TkApp
    result = await agr_07(driver, url, capítulo, ate)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\****\AppData\Local\Temp\main.py", line 2045, in agr_07
    result = await run(url, numero_capitulo, session)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\****\AppData\Local\Temp\main.py", line 1939, in run
    download_button = driver.find_element(By.CLASS_NAME, "download-direct")
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\****\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 741, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\****\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\Users\****\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":".download-direct"}
  (Session info: chrome=119.0.6045.160); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
        GetHandleVerifier [0x00007FF7A0F482B2+55298]
        (No symbol) [0x00007FF7A0EB5E02]
        (No symbol) [0x00007FF7A0D705AB]
        (No symbol) [0x00007FF7A0DB175C]
        (No symbol) [0x00007FF7A0DB18DC]
        (No symbol) [0x00007FF7A0DECBC7]
        (No symbol) [0x00007FF7A0DD20EF]
        (No symbol) [0x00007FF7A0DEAAA4]
        (No symbol) [0x00007FF7A0DD1E83]
        (No symbol) [0x00007FF7A0DA670A]
        (No symbol) [0x00007FF7A0DA7964]
        GetHandleVerifier [0x00007FF7A12C0AAB+3694587]
        GetHandleVerifier [0x00007FF7A131728E+4048862]
        GetHandleVerifier [0x00007FF7A130F173+4015811]
        GetHandleVerifier [0x00007FF7A0FE47D6+695590]
        (No symbol) [0x00007FF7A0EC0CE8]
        (No symbol) [0x00007FF7A0EBCF34]
        (No symbol) [0x00007FF7A0EBD062]
        (No symbol) [0x00007FF7A0EAD3A3]
        BaseThreadInitThunk [0x00007FFA2FAC7344+20]
        RtlUserThreadStart [0x00007FFA2FC026B1+33]

**Comment by OneDefauter** [comment]
Esse erro acontece quando o código vai baixar a imagem, mas o botão para baixar não apareceu.
Acredito que já corrigi com a atualização que fiz hoje, caso não tenha corrigido tente desativa a opção "Navegador em segundo plano" caso esteja ativado.

**Comment by Trademarkpolicyy** [comment]
@OneDefauter  aqui abre o capitulo ai depois abre uma pagina do capitulo em outra janela do navegador, da erro e nao baixa nenhuma

**Comment by OneDefauter** [comment]
Você poderia mandar dois vídeos mostrando?
Um vídeo com a opção Navegador em segundo plano ativado e outro Desativado.

**Comment by Trademarkpolicyy** [comment]
@OneDefauter 
https://streamin.one/v/31398a03
https://streamin.one/v/e28b07e6

**Comment by OneDefauter** [comment]
Fiz uma atualização que acredito que tenha corrigido isso e melhorei a velocidade para obter os capítulos.
