### ISSUE TITLE
Novo Barreira no brmangas.net

### ISSUE THREAD

**Issue by Trademarkpolicyy** [OneDefauter/Manga-Downloader#4]
brmangas.net criou outra barreira (protetor de link) pra entrar nos capitulos acho q isso ocasionou um novo erro:

Exception in thread Thread-4 (run_async_loop):
Traceback (most recent call last):
  File "C:\Users\rafae\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1052, in _bootstrap_inner
    self.run()
  File "C:\Users\rafae\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 989, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\rafae\AppData\Local\Temp\main.py", line 3177, in run_async_loop
    loop.run_until_complete(self.TkApp())
  File "C:\Users\rafae\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 664, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\rafae\AppData\Local\Temp\main.py", line 3010, in TkApp
    result = await agr_01(driver, url, capítulo, ate)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rafae\AppData\Local\Temp\main.py", line 897, in agr_01
    await run(url, numero_capitulo, session)
  File "C:\Users\rafae\AppData\Local\Temp\main.py", line 867, in run
    mudar()
  File "C:\Users\rafae\AppData\Local\Temp\main.py", line 815, in mudar
    select_modo_leitura = driver.find_element(By.ID, 'modo_leitura')
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rafae\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 741, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rafae\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\Users\rafae\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="modo_leitura"]"}
  (Session info: chrome=119.0.6045.199); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
        GetHandleVerifier [0x00007FF654CE82B2+55298]
        (No symbol) [0x00007FF654C55E02]
        (No symbol) [0x00007FF654B105AB]
        (No symbol) [0x00007FF654B5175C]
        (No symbol) [0x00007FF654B518DC]
        (No symbol) [0x00007FF654B8CBC7]
        (No symbol) [0x00007FF654B720EF]
        (No symbol) [0x00007FF654B8AAA4]
        (No symbol) [0x00007FF654B71E83]
        (No symbol) [0x00007FF654B4670A]
        (No symbol) [0x00007FF654B47964]
        GetHandleVerifier [0x00007FF655060AAB+3694587]
        GetHandleVerifier [0x00007FF6550B728E+4048862]
        GetHandleVerifier [0x00007FF6550AF173+4015811]
        GetHandleVerifier [0x00007FF654D847D6+695590]
        (No symbol) [0x00007FF654C60CE8]
        (No symbol) [0x00007FF654C5CF34]
        (No symbol) [0x00007FF654C5D062]
        (No symbol) [0x00007FF654C4D3A3]
        BaseThreadInitThunk [0x00007FFB01577344+20]
        RtlUserThreadStart [0x00007FFB027626B1+33]

**Comment by OneDefauter** [comment]
Está resolvido, até o momento.
